//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class cities_weather
    {
        public string CityId { get; set; }
        public string Temperature { get; set; }
        public string WeatherText { get; set; }
        public string Date { get; set; }
    }
}
